services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "28017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
